default:
  before_script:
  - apt-get update -qy
  - apt-get install -y python-yaml

test:
  script:
  - python simulation.py --num-simulations 5 --num-shipments 50 --config-file config.yml

linting:
  before_script:
  - python -m pip install --upgrade pip
  - pip install flake8
  script:
  - flake8 .

data:
  script:
  - ./generate_synthetic_F280_dataset.sh synthetic_records.csv 1000
  artifacts:
    paths:
    - synthetic_records.csv
  only:
  - master
