default:
  image: python:3.8
  before_script:
  - pip install yaml

test:
  script:
  - python simulation.py --num-simulations 5 --num-shipments 50 --config-file config.yml

linting:
  before_script:
  - pip install yaml flake8
  script:
  - flake8 .

data:
  script:
  - ./generate_synthetic_F280_dataset.sh synthetic_records.csv 1000
  artifacts:
    paths:
    - synthetic_records.csv
  only:
  - master
