default:
  image: python:3.8
  before_script:
  - pip install numpy scipy PyYAML

test:
  script:
  - python -m pathways --num-simulations 5 --num-shipments 50 --config-file config.yml

linting:
  before_script:
  - pip install numpy scipy PyYAML flake8 pylint black
  script:
  - flake8 .
  - pylint pathways
  - black --check --diff .

data:
  script:
  - ./generate_synthetic_F280_dataset.sh synthetic_records.csv 1000
  artifacts:
    paths:
    - synthetic_records.csv
  only:
  - master
