before_script:
  - apt-get update -qy
  - apt-get install -y pep8 python-yaml

test:
  script:
  - python simulation.py --num-simulations 5 --num-shipments 50 --config-file config.yml

linting:
  script:
  - pep8 --max-line-length=88 simulation.py

data:
  script:
  - ./generate_synthetic_F280_dataset.sh synthetic_records.csv 1000
  artifacts:
    paths:
    - synthetic_records.csv
  only:
  - master
