shipment:
  origins:
  - Netherlands
  - Mexico
  - Israel
  - Japan
  - New Zealand
  - India
  - Tanzania
  flowers:
  - Hyacinthus
  - Rosa
  - Gerbera
  - Agapanthus
  - Aegilops
  - Protea
  - Liatris
  - Mokara
  - Anemone
  - Actinidia
  pest:
    probability: 0.2
    ratio: 0.5
  boxes:
    min: 1
    max: 50
inspection:
  strategy: percentage
  percentage:
      proportion: 0.02
      min_boxes: 1
      end_strategy: to_completion
ports:
  - NY JFK CBP
  - FL Miami Air CBP
  - HI Honolulu CBP
  - AZ Phoenix CBP
  - VA Dulles CBP
  - CA San Francisco CBP
  - WA Seattle Air CBP
  - TX Brownsville CBP
  - WA Blaine CBP
# input_F280: F280_sample.csv
stems_per_box:
  default: 200
  air:
    default: 200
  maritime:
    default: 700
