shipment:
  origins:
  - Argentina
  - Estonia
  - Taiwan
  - Hawaii
  flowers:
  - Gloriosa
  - Gladiolus
  - Acer
  - Actinidia
  - Aegilops
  - Ananas
  pest:
    probability: 0.2
    ratio: 0.5
  boxes:
    min: 1
    max: 50
inspection:
  cfrp:
    flowers:
    - Gloriosa
    - Gladiolus
    - Acer
    - Actinidia
    max_boxes: 10
  first_n_boxes: 2
ports:
  - RDU
  - Miami
