shipment:
  origins:
  - Argentina
  - Estonia
  - Taiwan
  - Hawaii
  flowers:
  - Rose
  - Tulip
  - Acer
  - Actinidia
  - Aegilops
  - Ananas
  pest:
    probability: 0.2
    ratio: 0.5
  boxes:
    min: 1
    max: 50
