name: Deploy gh-pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Copy the page as index.html
      run: |
        mkdir artifacts
        ./generate_synthetic_F280_dataset.sh artifacts/synthetic_records.csv 1000
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./artifacts
        force_orphan: true
